# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Copyright © 2023 Erez Geva <ErezGeva2@gmail.com>
#
# @author Erez Geva <ErezGeva2@@gmail.com>
# @copyright © 2023 Erez Geva
#
# Test with Linuxptp and clock simulated network
# We run 2 tests
# * Full test with valgrind
# * Address Sanitizer
###############################################################################

name: linuxptp with dummy clock

# Start manually
on: workflow_dispatch

permissions:
  contents: read

jobs:
  full:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/deb.trixie:latest

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - name: checkout linuxptp repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        repository: richardcochran/linuxptp
        path: linuxptp

    - name: checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        path: libptpmgmt

    - name: test with linuxptp
      run: libptpmgmt/tools/sim_ptp4l.sh -c

  deb:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/deb.trixie:latest

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - name: checkout linuxptp repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        repository: richardcochran/linuxptp
        path: linuxptp

    - name: checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        path: libptpmgmt

    - name: test with linuxptp
      run: |
        make deb -C libptpmgmt
        dpkg -i *.deb
        make clean -C libptpmgmt
        libptpmgmt/tools/sim_ptp4l.sh -s

  adress:
    runs-on: ubuntu-latest

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - name: checkout linuxptp repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        repository: richardcochran/linuxptp
        path: linuxptp

    - name: checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        path: libptpmgmt

    - name: test with linuxptp
      run: libptpmgmt/tools/github_address.sh
